# Generated by Django 5.0 on 2023-12-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Errors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_code", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("reception_date", models.DateField()),
                (
                    "error_level",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("Important", "Important"),
                            ("Minor", "Minor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("Interface", "Interface"), ("Data", "Data")],
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("User", "User"), ("Tester", "Tester")], max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Programmers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programmer_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="ErrorFixes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fix_code", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                (
                    "fix_duration",
                    models.CharField(
                        choices=[("1 day", "1 day"), ("2 days", "2 days")],
                        max_length=10,
                    ),
                ),
                ("cost_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "error",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ErrorLogs.errors",
                    ),
                ),
                (
                    "programmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ErrorLogs.programmers",
                    ),
                ),
            ],
        ),
    ]
